name: CD Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            set -euo pipefail
            cd ./weatherApp
          
            docker stop weather-app || true
            docker rm weather-app || true
            
            git reset --hard HEAD~1
            git pull origin main
          
            if [ -f .env ]; then
              grep -v -e '^WEATHER_API_KEY=' -e '^LOCATION_BY_LOCATION_NAME_API_USERNAME=' .env > .env.tmp
              mv .env.tmp .env
            fi
            echo "WEATHER_API_KEY=${{ secrets.WEATHER_API_KEY }}" >> .env
            echo "LOCATION_BY_LOCATION_NAME_API_USERNAME=${{ secrets.LOCATION_BY_LOCATION_NAME_API_USERNAME }}" >> .env
          
            docker build --network=host -t weather-app .
          
            docker run -d \
              --restart unless-stopped \
              -p 3000:3000 \
              --env-file .env \
              --name weather-app \
              weather-app
          EOF